[versions]
agp = "8.13.2"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
hilt = "2.57.2"
hiltExt = "1.3.0"
room = "2.8.4"
ktorBom = "3.3.3"
kotlin-coroutines = "1.10.2"
kotlin-serialization = "1.9.0"
androidx-lifecycle-compose = "2.10.0"
androidx-work-manager = "2.11.0"
splashscreen = "1.2.0"
timber = "5.0.1"
playServicesLocation = "21.3.0"
maps = "7.0.0"
datastorePreferences = "1.2.0"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# ViewModel
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-compose" }
androidx-lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-compose" }

# WorkManager
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work-manager" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltExt" }
hilt-ext-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltExt" }

#Google
google-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
google-maps = { module = "com.google.maps.android:maps-compose", version.ref = "maps" }
google-mapsUtils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "maps" }

# Timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Jetbrains
# Coroutines
jetbrains-kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
jetbrains-kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

# Serialization
jetbrains-kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }

# Ktor
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktorBom" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-client-engine-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
ktor-client-plugin-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-plugin-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-client-plugin-kotlinx-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-client-plugin-contentEncoding = { group = "io.ktor", name = "ktor-client-encoding" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

